### ISSUE TITLE
PHP Fatal error:  Class 'App\Transformers\UserTransformer' not found 

### ISSUE THREAD

**Issue by agentelinux** [avew/simple-api-with-laravel5#1]
Laravel development server started on http://localhost:8000/
[Sun Aug 21 20:26:57 2016] PHP Fatal error:  Class 'App\Transformers\UserTransformer' not found in /simple-api-with-laravel5/app/Http/Controllers/Api/UsersController.php on line 38

**Comment by agentelinux** [comment]
I resolved.

edit the file composer.json

```
"autoload": {
    "classmap": [
        "database",
```

ADD -->        **"app/transformers"**

and run command:

$ composer dump-autoload

**Comment by avew** [comment]
@agentelinux : thx for correct, i forgot to add transformers to composer

**Comment by SaraVaseei** [comment]
I'd done the same mistake, you helped me a lot. Thanks @agentelinux !
